# -*- coding: utf-8 -*-
"""DT_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWGns8ZVlqwNnVIe9qwJY5P2JmfRevSq
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd  
df = pd.read_csv("Cricket.csv")  
df.shape
df.head()

# Label encode
from sklearn.preprocessing import LabelEncoder 
LE = LabelEncoder()
df['Gender'] = LE.fit_transform(df['Gender'])
df['Class'] = LE.fit_transform(df['Class'])
df.head()

X = df.drop('Cricket', axis=1) 
Y = df['Cricket']



# model fitting
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier(criterion='entropy', max_depth=1) 
classifier.fit(X, Y)

print("Node counts:",classifier.tree_.node_count)
print("max depth:",classifier.tree_.max_depth)

Y_pred = classifier.predict(X) 
from sklearn.metrics import accuracy_score
accuracy_score(Y,Y_pred).round(2)

from sklearn import tree
import graphviz 
dot_data = tree.export_graphviz(classifier, out_file=None, 
                    filled=True, rounded=True,  
                    special_characters=False)  
graph = graphviz.Source(dot_data)  
graph

import numpy as np
t1 = np.array([[0,0]])  # female, IX
t2 = np.array([[0,1]])  # female, X
t3 = np.array([[1,0]])  # male, IX
t4 = np.array([[1,1]])  # male, X

classifier.predict(t4)